version: '3.8'

services:
  db:
    image: postgres:16
    container_name: budget-db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: budget_db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: budget_backend
    container_name: budget-backend
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://admin:password@db:5432/budget_db
    ports:
      - "8000:8000"
    command: poetry run start-backend

  frontend:
    build: budget_frontend
    container_name: budget-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "8501:8501"
    command: poetry run start-frontend

volumes:
  db_data:
